const ADD_PLAYER = 'ADD_PLAYER';
const DELETE_PLAYER = 'DELETE_PLAYER';
const FETCH_PLAYERS = 'FETCH_PLAYERS';

const PIN_TEAMS = 'PIN_TEAMS';
const FETCH_PINNED_TEAM = 'FETCH_PINNED_TEAM';

const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const LOGOUT = 'LOGOUT';

const LOADER = 'LOADER';

const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';

export {
    ADD_PLAYER,
    DELETE_PLAYER,
    FETCH_PLAYERS,
    PIN_TEAMS,
    FETCH_PINNED_TEAM,
    LOADER,
    LOGIN,
    LOGOUT,
    SIGNUP,
    SUCCESS,
    ERROR
}